/**
 * ERP May 10 - Enterprise Menu Navigation Structure
 * Business-first categorization with strict RBAC permission mapping.
 */

export const ENTERPRISE_MENU = [
  {
    group: 'TỔNG QUAN',
    items: [
      {
        id: 'home',
        title: 'Trang chủ',
        path: '/',
        icon: 'LayoutDashboard',
        permission: 'dashboard.view',
      },
    ],
  },
  {
    group: 'KINH DOANH',
    permission: 'sales.view',
    items: [
      {
        id: 'sales-overview',
        title: 'Tổng quan bán hàng',
        path: '/sales',
        icon: 'LayoutDashboard',
        permission: 'sales.view',
      },
      {
        id: 'sales-customers',
        title: 'Khách hàng',
        path: '/sales/customers',
        icon: 'Users',
        permission: 'sales.view',
      },
      {
        id: 'sales-products',
        title: 'Sản phẩm',
        path: '/sales/products',
        icon: 'Package',
        permission: 'sales.view',
      },
      {
        id: 'sales-orders',
        title: 'Bán hàng & Đơn hàng',
        path: '/sales/orders',
        icon: 'ShoppingBag',
        permission: 'sales.view',
      },
      {
        id: 'sales-deliveries',
        title: 'Giao hàng',
        path: '/sales/deliveries',
        icon: 'ShoppingCart',
        permission: 'sales.view',
      },
      {
        id: 'sales-invoices',
        title: 'Hóa đơn bán hàng',
        path: '/sales/invoices',
        icon: 'DollarSign',
        permission: 'sales.view',
      },
      {
        id: 'sales-receivables',
        title: 'Công nợ phải thu',
        path: '/sales/receivables',
        icon: 'CreditCard',
        permission: 'sales.view',
      },
    ],
  },
  {
    group: 'SẢN XUẤT',
    permission: 'production.view',
    items: [
      {
        id: 'production-dashboard',
        title: 'Tổng quan',
        path: '/production',
        icon: 'LayoutDashboard',
        permission: 'production.view',
      },
      {
        id: 'production-plan',
        title: 'Kế hoạch sản xuất',
        path: '/production/plans',
        icon: 'CalendarDays',
        permission: 'production.view',
      },
      {
        id: 'production-bom',
        title: 'Định mức BOM',
        path: '/production/bom',
        icon: 'Layers',
        permission: 'production.view',
      },
      {
        id: 'production-orders',
        title: 'Lệnh sản xuất (LSX)',
        path: '/production/orders',
        icon: 'Factory',
        permission: 'production.view',
      },
      {
        id: 'production-mrp',
        title: 'Hoạch định MRP',
        path: '/production/mrp',
        icon: 'Cpu',
        permission: 'production.view',
      },
      {
        id: 'production-progress',
        title: 'Tiến độ & Quyết toán',
        path: '/production/progress',
        icon: 'BarChart3',
        permission: 'production.view',
      },
    ],
  },
  {
    group: 'MUA HÀNG',
    permission: 'purchasing.view',
    items: [
      {
        id: 'purchasing-dashboard',
        title: 'Tổng quan',
        path: '/purchasing',
        icon: 'LayoutDashboard',
        permission: 'purchasing.view',
      },
      {
        id: 'purchasing-suppliers',
        title: 'Nhà cung cấp',
        path: '/purchasing/suppliers',
        icon: 'Building2',
        permission: 'purchasing.view',
      },
      {
        id: 'purchasing-requisitions',
        title: 'Yêu cầu mua sắm (PR)',
        path: '/purchasing/requisitions',
        icon: 'ClipboardList',
        permission: 'purchasing.view',
      },
      {
        id: 'purchasing-rfq',
        title: 'Báo giá & So sánh (RFQ)',
        path: '/purchasing/rfqs',
        icon: 'Scale',
        permission: 'purchasing.view',
      },
      {
        id: 'purchasing-orders',
        title: 'Đơn mua hàng (PO)',
        path: '/purchasing/purchase-orders',
        icon: 'ShoppingCart',
        permission: 'purchasing.view',
      },
      {
        id: 'purchasing-receiving',
        title: 'Chờ nhập kho',
        path: '/purchasing/receiving',
        icon: 'Truck',
        permission: 'purchasing.view',
      },
      {
        id: 'purchasing-reports',
        title: 'Báo cáo',
        path: '/purchasing/reports',
        icon: 'BarChart3',
        permission: 'purchasing.view',
      },
    ],
  },
  {
    group: 'KHO & VẬT TƯ',
    permission: 'warehouse.view',
    items: [
      {
        id: 'wh-dashboard',
        title: 'Tổng quan kho',
        path: '/warehouse?tab=dashboard',
        icon: 'Warehouse',
        permission: 'warehouse.view',
      },
      {
        id: 'wh-ton-kho',
        title: 'Tồn kho & Thẻ kho',
        path: '/warehouse?tab=ton-kho',
        icon: 'Package',
        permission: 'warehouse.view',
      },
      {
        id: 'wh-vi-tri',
        title: 'Vị trí kho',
        path: '/warehouse?tab=vi-tri',
        icon: 'Layers',
        permission: 'warehouse.view',
      },
      {
        id: 'wh-lo-vat-tu',
        title: 'Lô vật tư & Cây vải',
        path: '/warehouse?tab=lo-vat-tu',
        icon: 'Tag',
        permission: 'warehouse.view',
      },
      {
        id: 'wh-cho-nhap',
        title: 'Chờ nhập kho',
        path: '/warehouse?tab=cho-nhap',
        icon: 'Truck',
        permission: 'warehouse.receipt',
      },
      {
        id: 'wh-phieu-nhap',
        title: 'Phiếu nhập kho',
        path: '/warehouse?tab=phieu-nhap',
        icon: 'ArrowDownLeft',
        permission: 'warehouse.receipt',
      },
      {
        id: 'wh-phieu-xuat',
        title: 'Phiếu xuất kho',
        path: '/warehouse?tab=phieu-xuat',
        icon: 'ArrowUpRight',
        permission: 'warehouse.issue',
      },
      {
        id: 'wh-phieu-chuyen',
        title: 'Điều chuyển kho',
        path: '/warehouse?tab=phieu-chuyen',
        icon: 'RefreshCw',
        permission: 'warehouse.transfer',
      },
      {
        id: 'wh-kiem-ke',
        title: 'Kiểm kê kho',
        path: '/warehouse?tab=kiem-ke',
        icon: 'ClipboardCheck',
        permission: 'warehouse.stocktake',
      },
    ],
  },
  {
    group: 'TÀI CHÍNH',
    permission: 'accounting.view',
    items: [
      {
        id: 'acc-dashboard',
        title: 'Tổng quan kế toán',
        path: '/accounting',
        icon: 'LayoutDashboard',
        permission: 'accounting.view',
      },
      {
        id: 'acc-documents',
        title: 'Chứng từ gốc',
        path: '/accounting/chung-tu',
        icon: 'FileText',
        permission: 'accounting.view',
      },
      {
        id: 'acc-journal',
        title: 'Hạch toán',
        path: '/accounting/hach-toan',
        icon: 'BookOpen',
        permission: 'accounting.journal',
      },
      {
        id: 'acc-ledger',
        title: 'Nhật ký và Sổ cái',
        path: '/accounting/so-cai',
        icon: 'Calculator',
        permission: 'accounting.journal',
      },
      {
        id: 'acc-debts',
        title: 'Quản lý Công nợ',
        path: '/accounting/cong-no',
        icon: 'CreditCard',
        permission: 'accounting.view',
      },
      {
        id: 'acc-costs',
        title: 'Tập hợp Chi phí',
        path: '/accounting/chi-phi',
        icon: 'DollarSign',
        permission: 'accounting.cost',
      },
      {
        id: 'acc-costing',
        title: 'Tính Giá thành SP',
        path: '/accounting/gia-thanh',
        icon: 'Scale',
        permission: 'accounting.cost',
      },
      {
        id: 'acc-order-eff',
        title: 'Hiệu quả đơn hàng',
        path: '/accounting/hieu-qua-don-hang',
        icon: 'BarChart3',
        permission: 'orderEfficiency.view',
      },
      {
        id: 'acc-reports',
        title: 'Báo cáo tài chính',
        path: '/accounting/bao-cao-tai-chinh',
        icon: 'ClipboardList',
        permission: 'accounting.reports',
      },
    ],
  },
  {
    group: 'QUẢN TRỊ',
    permission: 'admin.users',
    items: [
      {
        id: 'admin-users',
        title: 'Người dùng',
        path: '/admin/users',
        icon: 'Users',
        permission: 'admin.users',
      },
      {
        id: 'admin-permissions',
        title: 'Vai trò & phân quyền',
        path: '/admin/permissions',
        icon: 'ShieldCheck',
        permission: 'admin.permissions',
      },
    ],
  },
];
