import { Fragment, useEffect, useMemo, useRef, useState } from 'react';
import Icon from '../components/Icon.jsx';
import { money } from '../components/DocumentDetail.jsx';
import { fetchCosting, fetchCostingFilters } from '../services/costing.js';
import CostingCalculator from '../components/CostingCalculator.jsx';
import CostingResultsManager from '../components/CostingResultsManager.jsx';
import './Costing.css';

const now=new Date();
const initial={mode:'month',month:String(now.getMonth()+1),quarter:String(Math.floor(now.getMonth()/3)+1),year:String(now.getFullYear()),objectId:'',q:'',status:'',page:1,pageSize:20};
const has=value=>value!==null&&value!==undefined;
const pct=(value,total)=>Number(total)>0?Math.round(Number(value)/Number(total)*100):0;

function range(query){
  const year=Number(query.year);
  const formatDate=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
  if(query.mode==='month'){const month=Number(query.month);return{from:`${year}-${String(month).padStart(2,'0')}-01`,to:formatDate(new Date(year,month,0))};}
  if(query.mode==='quarter'){const month=(Number(query.quarter)-1)*3;return{from:formatDate(new Date(year,month,1)),to:formatDate(new Date(year,month+3,0))};}
  return{from:`${year}-01-01`,to:`${year}-12-31`};
}
function apiParams(query){const dates=range(query);return{...(query.q?{q:query.q}:{}),...(query.objectId?{objectId:query.objectId}:{}),...(query.status?{status:query.status}:{}),from:dates.from,to:dates.to,page:query.page,pageSize:query.pageSize};}
function periodKey(query){if(query.mode==='month')return`Thang${String(query.month).padStart(2,'0')}/${query.year}`;if(query.mode==='quarter')return`Quy${query.quarter}/${query.year}`;return`Nam${query.year}`;}
function periodText(query){if(query.mode==='month')return`Tháng ${query.month} / ${query.year}`;if(query.mode==='quarter')return`Quý ${['I','II','III','IV'][Number(query.quarter)-1]} / ${query.year}`;return`Năm ${query.year}`;}
function dataStatus(item){if(item.gia_thanh_id)return['done',item.trang_thai_gia_thanh==='da_duyet'?'Đã duyệt':'Đã tính'];if(!has(item.so_luong_hoan_thanh)||Number(item.so_luong_hoan_thanh)<=0)return['warn','Thiếu sản lượng'];if(!Number(item.so_dong_nguon))return['warn','Thiếu chi phí'];return['info','Chưa tính'];}

function DataStatus({item}){const hasCost=Number(item?.so_dong_nguon)>0,hasQuantity=Number(item?.so_luong_hoan_thanh)>0,hasResult=Boolean(item?.gia_thanh_id);const quantityDiff=hasResult&&hasQuantity&&Number(item.so_luong_hoan_thanh)!==Number(item.so_luong_san_xuat);const materialDiff=hasResult&&hasCost&&has(item.chi_phi_vat_lieu_truc_tiep)&&Number(item.chi_phi_nvl_nguon)!==Number(item.chi_phi_vat_lieu_truc_tiep);const differs=quantityDiff||materialDiff;const states=[['Chi phí nguồn hiện tại',hasCost?'done':'unknown',hasCost?'Có dữ liệu':'Chưa có dữ liệu','layers'],['Sản lượng hiện tại',hasQuantity?'done':'unknown',hasQuantity?Number(item.so_luong_hoan_thanh).toLocaleString('vi-VN'):'Chưa có dữ liệu','package'],['Kết quả giá thành đã lưu',hasResult?'done':'unknown',hasResult?'Có':'Chưa có','calculator'],['Đối chiếu dữ liệu',differs?'warn':hasResult?'done':'unknown',differs?'Có chênh lệch':hasResult?'Không phát hiện chênh lệch':'Chưa thể đối chiếu','warning']];return <section className="costing-process panel"><header><div><h2>Trạng thái dữ liệu giá thành</h2><p>Phân biệt dữ liệu nguồn hiện tại và kết quả giá thành đã lưu.</p></div><div className="process-object"><strong>{item?.ma_lenh_san_xuat||'Chưa chọn đối tượng'}</strong>{hasResult&&<span>Kết quả đã lưu</span>}</div></header><div className="costing-data-states">{states.map(([label,state,value,icon])=><article className={state} key={label}><span><Icon name={icon}/></span><div><small>{label}</small><strong>{value}</strong></div></article>)}</div></section>}

function snapshotLabel(value){const match=/^Thang(\d{2})\/(\d{4})$/.exec(value||'');return match?`Snapshot Tháng ${match[1]}/${match[2]}`:value?`Snapshot ${value}`:'Kết quả đã lưu';}

function Breakdown({item}){const total=has(item?.tong_chi_phi)?Number(item.tong_chi_phi):null;const parts=[['Nguyên vật liệu trực tiếp',item?.chi_phi_vat_lieu_truc_tiep,'teal'],['Nhân công trực tiếp',item?.chi_phi_nhan_cong_truc_tiep,'indigo'],['Chi phí sản xuất chung',item?.chi_phi_san_xuat_chung,'amber']].filter(([,value])=>has(value));return <section className={`costing-workspace ${item?.gia_thanh_id?'':'is-empty'}`}><article className="panel costing-breakdown"><header><div><h2>Cấu thành giá thành đã lưu</h2><p>Các thành phần thuộc kết quả giá thành đã lưu của kỳ này.</p></div>{item?.gia_thanh_id&&<span>{snapshotLabel(item.ky_tinh_gia_thanh)}</span>}</header>{!parts.length?<div className="costing-empty compact"><Icon name="layers"/><div><h3>Chưa có dữ liệu cấu thành</h3><p>Chưa có dữ liệu cấu thành cho đối tượng này.</p></div></div>:<div className="breakdown-list">{parts.map(([label,value,tone])=><div key={label} className={tone}><div><strong>{label}</strong><b>{money(value)}</b></div><div className="breakdown-track"><i style={{width:`${total?pct(value,total):0}%`}}/></div><small>{total?`${pct(value,total)}% tổng giá thành đã lưu`:'Chưa xác định tỷ trọng'}</small></div>)}</div>}</article><article className="panel costing-equation"><header><div><h2>Kết quả giá thành đã lưu</h2><p>Snapshot kết quả đã ghi nhận trong cơ sở dữ liệu.</p></div>{item?.gia_thanh_id&&<span className="saved-badge">Kết quả đã lưu</span>}</header>{item?.gia_thanh_id?<><div className="equation-parts">{parts.map(([label,value])=><span key={label}><small>{label}</small><strong>{money(value)}</strong></span>)}</div><div className="equation-total"><small>TỔNG GIÁ THÀNH</small><strong>{has(item.tong_chi_phi)?money(item.tong_chi_phi):'—'}</strong></div><div className="equation-unit"><span><b>{has(item.tong_chi_phi)?money(item.tong_chi_phi):'—'}</b><small>Tổng giá thành đã lưu</small></span><i>÷</i><span><b>{has(item.so_luong_san_xuat)?Number(item.so_luong_san_xuat).toLocaleString('vi-VN'):'—'}</b><small>Sản lượng tính giá thành</small></span><i>=</i><span className="result"><b>{has(item.gia_thanh_don_vi)?money(item.gia_thanh_don_vi):'—'}</b><small>Giá thành đơn vị đã lưu</small></span></div><p className="saved-formula-note">Theo kết quả đã lưu</p></>:<div className="costing-empty compact"><Icon name="calculator"/><div><h3>Chưa có kết quả giá thành được lưu cho đối tượng này.</h3><p>Dữ liệu nguồn hiện tại được giữ nguyên và không được dùng để tự tính giá thành.</p></div></div>}</article></section>}

function SnapshotCheck({item}){if(!item?.gia_thanh_id||item.tong_chi_phi_khop!==false&&item.gia_thanh_don_vi_khop!==false)return null;return <section className="costing-comparison"><header><Icon name="warning"/><div><h2>Kết quả đã lưu không khớp công thức từ chính snapshot</h2><p>Hệ thống chỉ cảnh báo để đối soát, không tự tính lại hoặc ghi đè dữ liệu đã lưu.</p></div></header></section>}

function Comparison({item}){if(!item.gia_thanh_id)return null;const rows=[has(item.so_luong_hoan_thanh)&&has(item.so_luong_san_xuat)?['Sản lượng',Number(item.so_luong_san_xuat).toLocaleString('vi-VN'),Number(item.so_luong_hoan_thanh).toLocaleString('vi-VN'),Number(item.so_luong_san_xuat)!==Number(item.so_luong_hoan_thanh)]:null,Number(item.so_dong_nguon)>0&&has(item.chi_phi_vat_lieu_truc_tiep)?['Chi phí NVL',money(item.chi_phi_vat_lieu_truc_tiep),money(item.chi_phi_nvl_nguon),Number(item.chi_phi_vat_lieu_truc_tiep)!==Number(item.chi_phi_nvl_nguon)]:null].filter(Boolean);if(!rows.some(row=>row[3]))return null;return <section className="costing-comparison"><header><Icon name="warning"/><div><h2>Dữ liệu nguồn hiện tại khác với kết quả đã lưu</h2><p>Dữ liệu sản xuất và chi phí nguồn hiện tại đã thay đổi so với dữ liệu dùng cho kết quả giá thành đã lưu. Kết quả phía trên được giữ nguyên để đảm bảo tính lịch sử và đối soát.</p></div></header><div><span></span><strong>Kết quả đã lưu</strong><strong>Hiện tại</strong>{rows.map(([label,saved,current])=><Fragment key={label}><b>{label}</b><span>{saved}</span><span>{current}</span></Fragment>)}</div></section>}

function MissingResult({item,capabilities}){const checks=[['Sản lượng',has(item.so_luong_hoan_thanh)?`${Number(item.so_luong_hoan_thanh).toLocaleString('vi-VN')} sản phẩm`:'Chưa có dữ liệu',Number(item.so_luong_hoan_thanh)>0?'Đã có dữ liệu':'Thiếu sản lượng'],['Chi phí tập hợp',Number(item.so_dong_nguon)>0?money(item.chi_phi_nvl_nguon):'Chưa có dữ liệu',Number(item.so_dong_nguon)>0?'Đã có chi phí nguồn':'Chưa đủ dữ liệu'],['Phân bổ chi phí',capabilities?.allocationDetails===true?'Có dữ liệu':'Chưa có dữ liệu xác nhận',capabilities?.allocationDetails===true?'Đã có dữ liệu':'Chưa xác định'],['Kết quả giá thành','Chưa có','Chưa thể xác định']];return <section className="costing-missing-result"><header><span><Icon name="warning"/></span><div><small>TRẠNG THÁI TÍNH GIÁ THÀNH</small><h2>Chưa đủ điều kiện tính giá thành</h2><p>{item.ma_lenh_san_xuat} · {item.ten_san_pham}</p></div></header><p>Đối tượng hiện chưa đủ dữ liệu để xác định giá thành.</p><div>{checks.map(([label,value,status])=><article key={label}><small>{label}</small><strong>{value}</strong><span>{status}</span></article>)}</div></section>}

export default function Costing({ canApprove = false }){
  const[draft,setDraft]=useState(initial),[query,setQuery]=useState(initial),[filters,setFilters]=useState({objects:[],periods:[],capabilities:{}}),[state,setState]=useState({loading:true}),[selectedId,setSelectedId]=useState(null),[refresh,setRefresh]=useState(0);const detailRef=useRef(null);
  useEffect(()=>{const controller=new AbortController();fetchCostingFilters(controller.signal).then(data=>{if(data&&!controller.signal.aborted)setFilters(data)}).catch(error=>{if(!controller.signal.aborted)setState({error:error.message})});return()=>controller.abort()},[]);
  useEffect(()=>{const controller=new AbortController();setState({loading:true});fetchCosting(apiParams(query),controller.signal).then(data=>{if(!data||controller.signal.aborted)return;setState(data);setSelectedId(old=>data.data?.some(item=>String(item.lenh_san_xuat_id)===String(old))?old:data.data?.[0]?.lenh_san_xuat_id??null)}).catch(error=>{if(!controller.signal.aborted)setState({error:error.message})});return()=>controller.abort()},[query,refresh]);
  const rows=state.data||[],selected=useMemo(()=>rows.find(item=>String(item.lenh_san_xuat_id)===String(selectedId))||null,[rows,selectedId]);const submit=event=>{event.preventDefault();setQuery({...draft,page:1})};const openDetail=(event,id)=>{event.stopPropagation();setSelectedId(id);requestAnimationFrame(()=>detailRef.current?.scrollIntoView({behavior:'smooth',block:'start'}));};
  return <div className="costing-page"><header className="costing-page-header"><div><nav>Tài chính - Kế toán <span>›</span> Tính giá thành</nav><div><span><Icon name="calculator"/></span><section><h1>Tính giá thành</h1><p>Tổng hợp chi phí và xác định giá thành sản phẩm theo kỳ.</p></section></div></div><aside><small>KỲ ĐANG XEM</small><strong>{periodText(query)}</strong><span>Tính và lưu dự thảo</span></aside></header>
  <form className="panel costing-controls" onSubmit={submit}><div><small>KỲ TÍNH GIÁ THÀNH</small><nav>{[['month','Tháng'],['quarter','Quý'],['year','Năm']].map(([value,label])=><button type="button" className={draft.mode===value?'active':''} onClick={()=>setDraft(old=>({...old,mode:value}))} key={value}>{label}</button>)}</nav></div>{draft.mode==='month'&&<label><span>Tháng</span><select value={draft.month} onChange={event=>setDraft(old=>({...old,month:event.target.value}))}>{Array.from({length:12},(_,index)=><option value={index+1} key={index}>Tháng {index+1}</option>)}</select></label>}{draft.mode==='quarter'&&<label><span>Quý</span><select value={draft.quarter} onChange={event=>setDraft(old=>({...old,quarter:event.target.value}))}>{['I','II','III','IV'].map((value,index)=><option value={index+1} key={value}>Quý {value}</option>)}</select></label>}<label><span>Năm</span><select value={draft.year} onChange={event=>setDraft(old=>({...old,year:event.target.value}))}>{[now.getFullYear()-2,now.getFullYear()-1,now.getFullYear(),now.getFullYear()+1].map(year=><option key={year}>{year}</option>)}</select></label><label className="costing-object-select"><span>Đối tượng / sản phẩm</span><select value={draft.objectId} onChange={event=>setDraft(old=>({...old,objectId:event.target.value}))}><option value="">Tất cả đối tượng</option>{filters.objects.map(item=><option value={item.id} key={item.id}>{item.ma_lenh_san_xuat} · {item.ma_san_pham}</option>)}</select></label><button className="costing-view"><Icon name="search"/>Xem dữ liệu</button></form>
  <DataStatus item={selected}/>
  <section className="panel costing-objects"><header><div><h2>Đối tượng tính giá thành</h2><p>Sản phẩm và lệnh sản xuất phát sinh trong kỳ</p></div><form onSubmit={submit}><label><Icon name="search"/><input value={draft.q} onChange={event=>setDraft(old=>({...old,q:event.target.value}))} placeholder="Mã lệnh sản xuất, sản phẩm..."/></label><select value={draft.status} onChange={event=>setDraft(old=>({...old,status:event.target.value}))}><option value="">Tất cả trạng thái</option><option value="calculated">Đã tính</option><option value="missing">Chưa có kết quả</option></select></form></header>{state.loading?<div className="costing-state">Đang tải dữ liệu giá thành…</div>:state.error?<div className="costing-state error">{state.error}</div>:!rows.length?<div className="costing-empty"><Icon name="package"/><div><h3>Chưa có đối tượng tính giá thành trong kỳ này.</h3><p>Chưa tìm thấy lệnh sản xuất hoặc sản phẩm phù hợp với kỳ đã chọn.</p></div></div>:<div className="overflow-x-auto"><table className="erp-table costing-table"><thead><tr>{['Lệnh sản xuất','Sản phẩm','Sản lượng hiện tại','Đơn vị','Chi phí nguồn hiện tại','Trạng thái dữ liệu','Giá thành đơn vị đã lưu','Thao tác'].map(label=><th key={label} className={label.includes('Chi phí')||label.includes('Giá thành')?'text-right':'text-left'}>{label}</th>)}</tr></thead><tbody>{rows.map(item=>{const status=dataStatus(item);return <tr className={String(selectedId)===String(item.lenh_san_xuat_id)?'selected':''} key={item.lenh_san_xuat_id} onClick={()=>setSelectedId(item.lenh_san_xuat_id)}><td><button>{item.ma_lenh_san_xuat}</button></td><td><strong>{item.ma_san_pham}</strong><small>{item.ten_san_pham}</small></td><td>{has(item.so_luong_hoan_thanh)?Number(item.so_luong_hoan_thanh).toLocaleString('vi-VN'):'—'}</td><td>{item.ten_don_vi||'—'}</td><td className="amount">{Number(item.so_dong_nguon)?money(item.chi_phi_nvl_nguon):'—'}</td><td><span className={`costing-badge ${status[0]}`}>{status[1]}</span></td><td className="amount">{has(item.gia_thanh_don_vi)?money(item.gia_thanh_don_vi):'—'}</td><td><button className="detail-link" onClick={event=>openDetail(event,item.lenh_san_xuat_id)}>Xem chi tiết <Icon name="arrow"/></button></td></tr>})}</tbody></table></div>}</section>
  {selected&&<div ref={detailRef} className="costing-detail"><CostingCalculator item={selected} period={periodKey(query)} onSaved={()=>setRefresh(value=>value+1)}/><CostingResultsManager productionOrderId={selected.lenh_san_xuat_id} refreshKey={refresh} canApprove={canApprove} onChanged={()=>setRefresh(value=>value+1)}/><Breakdown item={selected}/>{selected.gia_thanh_id?<section className="costing-result"><header><span><Icon name="check"/></span><div><small>KẾT QUẢ GIÁ THÀNH ĐÃ LƯU</small><h2>{selected.ma_san_pham} · {selected.ten_san_pham}</h2></div><em>{snapshotLabel(selected.ky_tinh_gia_thanh)}</em></header><div>{[['Tổng chi phí được phân bổ',selected.tong_chi_phi,true],['Sản lượng tính giá thành',selected.so_luong_san_xuat,false],['Tổng giá thành',selected.tong_chi_phi,true],['Giá thành / sản phẩm',selected.gia_thanh_don_vi,true]].filter(([,value])=>has(value)).map(([label,value,isMoney])=><article key={label}><small>{label}</small><strong>{isMoney?money(value):Number(value).toLocaleString('vi-VN')}</strong><span>Theo kết quả đã lưu</span></article>)}</div></section>:<MissingResult item={selected} capabilities={filters.capabilities}/>}<SnapshotCheck item={selected}/><Comparison item={selected}/></div>}</div>
}
